services:
  libdinorunner:
    build: .
    user: dino_runner
    privileged: true
    volumes:
      - .:/home/dino_runner/dinorunner
    working_dir: /home/dino_runner/dinorunner
    command: >
      bash -c "cmake -DCMAKE_BUILD_TYPE=Release -S dinorunner -B dinorunner/build && cmake --build dinorunner/build"

  dinorunner:
    build: .
    user: dino_runner
    privileged: true
    network_mode: "host"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input:/dev/input
      - $HOME/.ssh:/home/dino_runner/.ssh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri 
      - $XDG_RUNTIME_DIR/pulse/native:$XDG_RUNTIME_DIR/pulse/native
      - .:/home/dino_runner/dinorunner
    environment:
      - DISPLAY=$DISPLAY
      - SSH_AUTH_SOCK=/tmp/ssh_auth_sock
      - XAUTHORITY=$XAUTHORITY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
    working_dir: /home/dino_runner/dinorunner
    depends_on:
      - libdinorunner
    command: >
      bash -c "cmake -DCMAKE_BUILD_TYPE=Release -S demo -B demo/build && cmake --build demo/build && demo/bin/dinorunner_sdl"
