version: '3'
services:
  dinorunner:
    build: .
    user: dino_runner
    environment:
      - DISPLAY=$DISPLAY
      - SSH_AUTH_SOCK=/tmp/ssh_auth_sock
      - XAUTHORITY=$XAUTHORITY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/dino_runner/dinorunner
      - /dev/dri:/dev/dri 
    working_dir: /home/dino_runner/dinorunner
    network_mode: "host"
    command: >
      bash -c "cmake -DCMAKE_BUILD_TYPE=Release -S demo -B demo/build && cmake --build demo/build && demo/bin/dinorunner_sdl"
