@PACKAGE_INIT@
set(DINORUNNER_INCLUDE_DIR "@PACKAGE_INCLUDE_INSTALL_DIR@")
set(DINORUNNER_SYSCONFIG_DIR "@PACKAGE_SYSCONFIG_INSTALL_DIR@")
set(DINORUNNER_INCLUDE_DIR "@CMAKE_INSTALL_FULL_INCLUDEDIR@/dinorunner/")
set(DINORUNNER_BINARY_DIR "@CMAKE_INSTALL_PREFIX@/lib")

check_required_components(dinorunner)